Update & Add Favicon & Shortcut icon
openintents/timesheet pull request #8
Opened 2018-12-03 14:37 UTC by davidyapdy

2018-12-03 15:50 UTC, friedger commented
Isn't it favico.ico instead of png?

2018-12-03 15:56 UTC, davidyapdy commented
@friedger added both.

2018-12-14 15:02 UTC, friedger requested changes
Please remove features.md here

2018-12-16 10:16 UTC, friedger commented
Sorry I got taken away with branching...
`timestacks` is on `develop`

2018-12-16 10:16 UTC, merged